name: Run ML Notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install -r requirements.txt
          pip install streamlit  # Install Streamlit for the app

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute notebook/diabetes_prediction_pipeline.ipynb --output executed_notebook.ipynb

      - name: Run Streamlit app
        run: |
          nohup streamlit run app/app.py &  # running Streamlit in the background
          echo $! > streamlit_pid.txt  # saviing the Streamlit process ID to a file
          sleep 10  # waiting for the app to start

      - name: Test Streamlit app
        run: |
          curl --silent --show-error --fail http://localhost:8501  # testing if the app is accessible

      - name: Kill Streamlit app (if running)
        run: |
          if [ -f streamlit_pid.txt ]; then  # check if the PID file exists
            kill $(cat streamlit_pid.txt)  # killing Streamlit using the saved process ID
            echo "Streamlit app killed successfully."
          else
            echo "Streamlit PID file not found. Skipping kill step."
          fi
